# This is a basic workflow to help you get started with Actions

name: CI

on: 
  push:
    branches:
      - production
      
jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # Generates a build number
      - name: Generate build number
        uses: einaregilsson/build-number@v2 
        id: buildnumber
        with:
          token: ${{secrets.github_token}}
      # Creates a new branch with the built number
      - name: Creates Branch with Release
        uses: peterjgrainger/action-create-branch@v1.0.0
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "production-release-${{ steps.buildnumber.outputs.build_number }}"
      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.cisasp.com
          server_port: 993
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result
          body: Release job of ${{github.repository}} completed successfully!
          to: gustavor@loymark.com
          from: githubaction@loymark.com