# This is a basic workflow to help you get started with Actions

name: CI

on: 
  push:
    branches:
      - production

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Generate build number
        uses: einaregilsson/build-number@v2 
        id: buildnumber
        with:
          token: ${{secrets.github_token}}
      # - uses: rymndhng/release-on-push-action@master
      #   with:
      #     bump_version_scheme: patch
      - uses: peterjgrainger/action-create-branch@v1.0.0
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "production-release-${{ steps.buildnumber.outputs.build_number }}"